# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'PJPageViewControllerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PJPageViewControllerExample
  pod 'PJPageViewController', :path => '../../PJPageViewController'
  pod 'LookinServer', :configurations => ['Debug']

end
